[package]
name = "incong"
version = "0.1.0"
edition = "2024"

[package.metadata.release]
release = false

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
itertools = { workspace = true }

automata = { path = "../../crates/automata" }
